/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

/**
 *
 * @author xatalie
 */
public class Utama extends javax.swing.JFrame {

    /**
     * Creates new form Utama
     */
    public Utama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollBar1 = new javax.swing.JScrollBar();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        background1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollBar2 = new javax.swing.JScrollBar();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        background3 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        backgrond3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(820, 500));

        jPanel1.setLayout(null);

        jPanel2.setLayout(null);
        jPanel2.add(jScrollBar1);
        jScrollBar1.setBounds(480, 0, 17, 470);

        jLabel10.setBackground(new java.awt.Color(0, 255, 51));
        jLabel10.setText("jLabel2");
        jLabel10.setOpaque(true);
        jLabel10.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel2.add(jLabel10);
        jLabel10.setBounds(350, 310, 100, 100);

        jLabel9.setBackground(new java.awt.Color(0, 204, 153));
        jLabel9.setText("jLabel2");
        jLabel9.setOpaque(true);
        jLabel9.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel2.add(jLabel9);
        jLabel9.setBounds(190, 310, 100, 100);

        jLabel8.setBackground(new java.awt.Color(0, 255, 51));
        jLabel8.setText("jLabel2");
        jLabel8.setOpaque(true);
        jLabel8.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel2.add(jLabel8);
        jLabel8.setBounds(30, 310, 100, 100);

        jLabel7.setBackground(new java.awt.Color(0, 204, 153));
        jLabel7.setText("jLabel2");
        jLabel7.setOpaque(true);
        jLabel7.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel2.add(jLabel7);
        jLabel7.setBounds(350, 170, 100, 100);

        jLabel6.setBackground(new java.awt.Color(0, 255, 51));
        jLabel6.setText("jLabel2");
        jLabel6.setOpaque(true);
        jLabel6.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel2.add(jLabel6);
        jLabel6.setBounds(190, 170, 100, 100);

        jLabel5.setBackground(new java.awt.Color(0, 204, 153));
        jLabel5.setText("jLabel2");
        jLabel5.setOpaque(true);
        jLabel5.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel2.add(jLabel5);
        jLabel5.setBounds(30, 170, 100, 100);

        jLabel4.setBackground(new java.awt.Color(0, 255, 51));
        jLabel4.setText("jLabel2");
        jLabel4.setOpaque(true);
        jLabel4.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel2.add(jLabel4);
        jLabel4.setBounds(350, 30, 100, 100);

        jLabel3.setBackground(new java.awt.Color(0, 204, 153));
        jLabel3.setText("jLabel2");
        jLabel3.setOpaque(true);
        jLabel3.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel2.add(jLabel3);
        jLabel3.setBounds(190, 30, 100, 100);

        jLabel2.setBackground(new java.awt.Color(0, 255, 51));
        jLabel2.setText("jLabel2");
        jLabel2.setOpaque(true);
        jLabel2.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel2.add(jLabel2);
        jLabel2.setBounds(30, 30, 100, 100);
        jPanel2.add(background1);
        background1.setBounds(0, 0, 490, 470);

        jTabbedPane1.addTab("Makanan", jPanel2);

        jPanel5.setLayout(null);
        jPanel5.add(jScrollBar2);
        jScrollBar2.setBounds(480, 0, 17, 470);

        jLabel11.setBackground(new java.awt.Color(0, 255, 51));
        jLabel11.setText("jLabel2");
        jLabel11.setOpaque(true);
        jLabel11.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel5.add(jLabel11);
        jLabel11.setBounds(350, 310, 100, 100);

        jLabel12.setBackground(new java.awt.Color(0, 204, 153));
        jLabel12.setText("jLabel2");
        jLabel12.setOpaque(true);
        jLabel12.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel5.add(jLabel12);
        jLabel12.setBounds(190, 310, 100, 100);

        jLabel13.setBackground(new java.awt.Color(0, 255, 51));
        jLabel13.setText("jLabel2");
        jLabel13.setOpaque(true);
        jLabel13.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel5.add(jLabel13);
        jLabel13.setBounds(30, 310, 100, 100);

        jLabel14.setBackground(new java.awt.Color(0, 204, 153));
        jLabel14.setText("jLabel2");
        jLabel14.setOpaque(true);
        jLabel14.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel5.add(jLabel14);
        jLabel14.setBounds(350, 170, 100, 100);

        jLabel15.setBackground(new java.awt.Color(0, 255, 51));
        jLabel15.setText("jLabel2");
        jLabel15.setOpaque(true);
        jLabel15.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel5.add(jLabel15);
        jLabel15.setBounds(190, 170, 100, 100);

        jLabel16.setBackground(new java.awt.Color(0, 204, 153));
        jLabel16.setText("jLabel2");
        jLabel16.setOpaque(true);
        jLabel16.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel5.add(jLabel16);
        jLabel16.setBounds(30, 170, 100, 100);

        jLabel17.setBackground(new java.awt.Color(0, 255, 51));
        jLabel17.setText("jLabel2");
        jLabel17.setOpaque(true);
        jLabel17.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel5.add(jLabel17);
        jLabel17.setBounds(350, 30, 100, 100);

        jLabel18.setBackground(new java.awt.Color(0, 204, 153));
        jLabel18.setText("jLabel2");
        jLabel18.setOpaque(true);
        jLabel18.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel5.add(jLabel18);
        jLabel18.setBounds(190, 30, 100, 100);

        jLabel19.setBackground(new java.awt.Color(0, 255, 51));
        jLabel19.setText("jLabel2");
        jLabel19.setOpaque(true);
        jLabel19.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel5.add(jLabel19);
        jLabel19.setBounds(30, 30, 100, 100);
        jPanel5.add(background3);
        background3.setBounds(0, 0, 490, 470);

        jTabbedPane1.addTab("Minuman", jPanel5);

        jPanel1.add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 0, 500, 500);

        jPanel3.setLayout(null);

        jLabel1.setText("Total");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(20, 420, 36, 15);
        jPanel3.add(jTextField1);
        jTextField1.setBounds(140, 420, 170, 19);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 310, 403);
        jPanel3.add(backgrond3);
        backgrond3.setBounds(0, 0, 310, 470);

        jTabbedPane2.addTab("Total Pembayaran", jPanel3);

        jPanel1.add(jTabbedPane2);
        jTabbedPane2.setBounds(500, 0, 320, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Utama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgrond3;
    private javax.swing.JLabel background1;
    private javax.swing.JLabel background3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollBar jScrollBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
